# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/laboratorio/exercicio_01/exercicio_01.cache/wt [current_project]
set_property parent.project_path C:/Users/laboratorio/exercicio_01/exercicio_01.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/laboratorio/exercicio_01/exercicio_01.srcs/sources_1/new/variaveis_ex.vhd
synth_design -top variaveis_ex -part xc7a100tcsg324-1
write_checkpoint -noxdef variaveis_ex.dcp
catch { report_utilization -file variaveis_ex_utilization_synth.rpt -pb variaveis_ex_utilization_synth.pb }
